# Project: Array10
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = array10.o main.o sbtrees.o
LINKOBJ  = array10.o main.o sbtrees.o
LIBS     = -L"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/lib" -L"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Array10.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = E:\Data Penting\ProgramFiles\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

array10.o: array10.c
	$(CC) -c array10.c -o array10.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

sbtrees.o: sbtrees.c
	$(CC) -c sbtrees.c -o sbtrees.o $(CFLAGS)
