# Project: Kasus 8
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o case8.o nbtrees.o
LINKOBJ  = main.o case8.o nbtrees.o
LIBS     = -L"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/lib" -L"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/Data Penting/ProgramFiles/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Kasus 8.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = E:\Data Penting\ProgramFiles\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

case8.o: case8.c
	$(CC) -c case8.c -o case8.o $(CFLAGS)

nbtrees.o: nbtrees.c
	$(CC) -c nbtrees.c -o nbtrees.o $(CFLAGS)
